export const WEBSOCKET_NEW_CONNECTION_MADE = 'WEBSOCKET_NEW_CONNECTION_MADE';
export type WEBSOCKET_NEW_CONNECTION_MADE  = typeof WEBSOCKET_NEW_CONNECTION_MADE;
export const WEBSOCKET_MESSAGE_RECEIVED    = 'WEBSOCKET_MESSAGE_RECEIVED';
export type WEBSOCKET_MESSAGE_RECEIVED     = typeof WEBSOCKET_MESSAGE_RECEIVED;
export const WEBSOCKET_CONNECTION_CLOSED   = 'WEBSOCKET_CONNECTION_CLOSED';
export type WEBSOCKET_CONNECTION_CLOSED    = typeof WEBSOCKET_CONNECTION_CLOSED;
export const WEBSOCKET_CONNECTION_ERROR    = 'WEBSOCKET_CONNECTION_ERROR';
export type WEBSOCKET_CONNECTION_ERROR     = typeof WEBSOCKET_CONNECTION_ERROR;